### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by erfanz** [MParvin/shadowsocks-docker#1]
Content of `.env` on server **AND** client (identical):

> encryption_key=MY_KEY
> server_port=8488
> client_port=1080
> server_ip=SERVER_IP

Output of running `docker-compose -f docker-compose-server.yml up -d` on server:
> [+] Running 1/1
>  ⠿ Container shadowsocks-docker-socks-1  Started  

Output of running `sudo docker-compose -f docker-compose-client.yml up -d` on client:
> [+] Running 0/1
>  ⠿ shadowsocks-client Error                                                                                                             11.3s
> Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout

Client can ping server.

What could be the problem? Also, are the contents of .env on client and server supposed to be identical?

**Comment by MParvin** [comment]
This error is about downloading images from docker.com.(about the sanctions against Iran.)
To download docker images from Docker.com(In your Iran server), Please use VPN, Proxy, or shecan.ir.
